### PR TITLE
only use sudo in nuke command on darwin

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by staticfloat** [comment]
We need to do this on the CentOS builders as well, but this is a good start.

**Comment by tkelman** [comment]
Was causing an issue on centos 5 apparently? 136cdb040cd0b1e3704d213dfee9ee9c9b4fd483

http://buildbot.e.ip.saba.us:8010/builders/nuke_centos5.11-x64/builds/3/steps/Do%20your%20thing%2C%20Duke/logs/stdio

**Comment by staticfloat** [comment]
Yerp. There might be a flash we should be sending to sudo to get around this maybe?

**Comment by tkelman** [comment]
or a buildbot configuration somewhere, considering the `using PTY: False` ...

**Pull request merged**
