### PR TITLE
use --precompiled=no instead of deleting sys.so for coverage

### PR DESCRIPTION
**Pull request by tkelman**
cc @staticfloat @kshyatt we're not currently building coverage for the release branch, so don't think we need to worry too much about compatibility here

### CODE REVIEW

**Comment by kshyatt** [comment]
Coverage is currently not working anyway due to the `utf16_is_surrogate` deprecation in JSON.jl that just got fixed.

**Comment by tkelman** [comment]
I trust that will be fixed before too long.

**Comment by kshyatt** [comment]
It was just fixed today. FWIW I just ran coverage on OSX with latest master with no issues.

**Comment by tkelman** [comment]
Did you need `--output-ji` ?

**Comment by kshyatt** [comment]
I'm honestly unsure. I've made the same changes you have here to my `run_coverage.sh` script and we'll see if it works!

**Comment by kshyatt** [comment]
:tada: Ok so not only did this work on OSX, but it removed most of the disparity between our OSX and Linux coverage runs.

**Comment by staticfloat** [comment]
Thanks guys!

**Pull request merged**
