### PR TITLE
Updated merging coverage files

### PR DESCRIPTION
**Pull request by kshyatt**
The CoverageBase and Coverage syntax has changed. I've updated the buildbot script so everything should run ok now!

### CODE REVIEW

**Comment by staticfloat** [comment]
So previously, we would run `Coveralls.process()` which would save out `coveralls.jld`, and we would run `Codecov.process()` which would save out `codecov.jld`.  We'd then move those files to `<prefix>_nonlined.jld`, and merge them in with their own separate `merge()` commands.  Throughout this whole process, `Coveralls` and `Codecov` had separate pipelines, as it were.

Now, you've merged the merge step such that the `results` variable is reading in from `coveralls_*.jld` only.  As that is the case, can we get rid of the `codecov_*.jld` files completely?  Could we not call them `coveralls_*.jld` at all, and just call them `coverage.jld`, `coverage_noninlined.jld` and `coverage_inlined.jld`?

**Comment by kshyatt** [comment]
Oops! Yeah, we only need one set of `.jld`s because @IainNz refactored Coverage.jl.

**Comment by staticfloat** [comment]
lgtm!

**Comment by IainNZ** [comment]
#refactored #soclean #winning

**Pull request merged**
